=== raido-ddr/DarjaReentovich/Task4/web/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.raido.com/tariffs"
            xmlns:trns = "http://www.raido.com/tariffs"
            elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="trns:tariff"
                         minOccurs="1"
                         maxOccurs="unbounded"
                         />
            </sequence>
        </complexType>
    </element>

    <complexType name="Tariff" abstract="true">
        <sequence>
            <element name="id" >
                <simpleType>
                    <restriction base="ID">
                        <pattern value="([\w]{2,10})" />
                    </restriction>
                </simpleType>
            </element>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="\w{3,15}[,!?\+]*" />
                    </restriction>
                </simpleType>
            </element>
            <element name="monthly-fee" type="float" />
            <element name="sms-charge" type="float" />
        </sequence>
        <attribute name="status" type="trns:Status" use="optional" default="active"/>
    </complexType>

    <complexType name="LocalTariff">
        <complexContent>
            <extension base="trns:Tariff">
                <sequence>
                    <element name="internal-charge" type="trns:CallCharge" />
                    <element name="external-charge" type="trns:CallCharge" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="RoamingTariff">
        <complexContent>
            <extension base="trns:Tariff">
                <sequence>
                    <element name="outgoing-charge" type="trns:CallCharge" />
                    <element name="incoming-charge" type="trns:CallCharge" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="NetworkingTariff">
        <complexContent>
            <extension base="trns:LocalTariff">
                <sequence>
                    <element name="connection-speed" type="trns:ConnectionSpeed" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="GuestTariff">
        <complexContent>
            <extension base="trns:LocalTariff">
                <sequence>
                    <element name="stay-length-discount" type="trns:Discount" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="BonusTariff">
        <complexContent>
            <extension base="trns:NetworkingTariff">
                <sequence>
                    <element name="free-minutes" type="positiveInteger" />
                    <element name="favourite-numbers" type="positiveInteger" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="ConnectionSpeed">
        <restriction base="float" >
            <minExclusive value="0" />
            <maxInclusive value="500" />
        </restriction>
    </simpleType>

    <simpleType name="CallCharge">
        <restriction base="float">
            <minInclusive value="0" />
        </restriction>
    </simpleType>

    <simpleType name="Discount">
        <restriction base="float">
            <maxExclusive value="100" />
        </restriction>
    </simpleType>

    <simpleType name="Status">
        <restriction base="string">
            <enumeration value="active"></enumeration>
            <enumeration value="supported"></enumeration>
            <enumeration value="unavailable"></enumeration>
        </restriction>
    </simpleType>

    <element name="tariff" type="trns:Tariff" abstract="true" />

    <element name="local-tariff" type="trns:LocalTariff" substitutionGroup="trns:tariff" />

    <element name="roaming-tariff" type="trns:RoamingTariff" substitutionGroup="trns:tariff" />

    <element name="networking-tariff" type="trns:NetworkingTariff" substitutionGroup="trns:tariff" />

    <element name="guest-tariff" type="trns:GuestTariff" substitutionGroup="trns:tariff" />

    <element name="bonus-tariff" type="trns:BonusTariff" substitutionGroup="trns:tariff" />

</schema>

=== raido-ddr/DarjaReentovich/Task4/web/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.raido.com/tariffs"
             xsi:schemaLocation="http://www.raido.com/tariffs tariffs.xsd">

    <local-tariff>
        <id>id1</id>
        <name>Hello</name>
        <monthly-fee>20.5</monthly-fee>
        <sms-charge>0.5</sms-charge>
        <internal-charge>3.7</internal-charge>
        <external-charge>2.5</external-charge>
    </local-tariff>

    <networking-tariff status="supported">
        <id>id2</id>
        <name>MobileNet</name>
        <monthly-fee>28.5</monthly-fee>
        <sms-charge>0.4</sms-charge>
        <internal-charge>2.6</internal-charge>
        <external-charge>3.8</external-charge>
        <connection-speed>100</connection-speed>
    </networking-tariff>

    <bonus-tariff status="unavailable">
        <id>id3</id>
        <name>Optimal</name>
        <monthly-fee>15</monthly-fee>
        <sms-charge>0.5</sms-charge>
        <internal-charge>3.5</internal-charge>
        <external-charge>4.7</external-charge>
        <connection-speed>100</connection-speed>
        <free-minutes>30</free-minutes>
        <favourite-numbers>5</favourite-numbers>
    </bonus-tariff>

    <roaming-tariff status="active">
        <id>id4</id>
        <name>International</name>
        <monthly-fee>0</monthly-fee>
        <sms-charge>5.5</sms-charge>
        <outgoing-charge>10</outgoing-charge>
        <incoming-charge>6</incoming-charge>
    </roaming-tariff>

    <guest-tariff>
        <id>id5</id>
        <name>Welcome</name>
        <monthly-fee>0</monthly-fee>
        <sms-charge>0.6</sms-charge>
        <internal-charge>2.5</internal-charge>
        <external-charge>3.4</external-charge>
        <stay-length-discount>15</stay-length-discount>
    </guest-tariff>

    <roaming-tariff status="active">
        <id>id6</id>
        <name>Visitor</name>
        <monthly-fee>0.5</monthly-fee>
        <sms-charge>4.0</sms-charge>
        <outgoing-charge>8</outgoing-charge>
        <incoming-charge>5</incoming-charge>
    </roaming-tariff>

</tariffs>
